// server/game/TapeCodec.js
//
// Encoding for the game log. Shared by the store (writes), the replayer
// (reads), and the exporter, so a change here changes all three together
// rather than one of them silently.
//
// Cards reuse the existing `value = rankIndex * 4 + suitIndex` (0-51) from
// Deck.js. No new card encoding exists anywhere in this system.

const { SUITS, RANKS } = require('./Deck');

const DECK_SIZE = 52;

// Card value -> the canonical {rank, suit, value} object. Built once; the
// objects are frozen because decoded hands flow into Big2Rules, which sorts
// and compares but must never mutate them.
const CARD_BY_VALUE = Array.from({ length: DECK_SIZE }, (_, value) => Object.freeze({
    rank: RANKS[Math.floor(value / 4)],
    suit: SUITS[value % 4],
    value
}));

const cardValue = (card) => RANKS.indexOf(card.rank) * 4 + SUITS.indexOf(card.suit);

/**
 * Deal -> 52-byte Buffer where deal[cardValue] = seat.
 *
 * Fixed width, order-independent, and canonical: two deals that differ only in
 * the order cards were dealt within a hand encode identically. That matters
 * because hands are sorted on deal, so ordering carries no information.
 */
function encodeDeal(handsBySeat) {
    const deal = Buffer.alloc(DECK_SIZE, 0xff);
    handsBySeat.forEach((hand, seat) => {
        for (const card of hand) {
            deal[card.value !== undefined ? card.value : cardValue(card)] = seat;
        }
    });
    const unassigned = deal.indexOf(0xff);
    if (unassigned !== -1) {
        throw new Error(`encodeDeal: card ${unassigned} was not dealt to any seat`);
    }
    return deal;
}

/** 52-byte Buffer -> four hands, each sorted by value as the game deals them. */
function decodeDeal(deal) {
    if (!deal || deal.length !== DECK_SIZE) {
        throw new Error(`decodeDeal: expected ${DECK_SIZE} bytes, got ${deal ? deal.length : 0}`);
    }
    const hands = [[], [], [], []];
    for (let value = 0; value < DECK_SIZE; value++) {
        const seat = deal[value];
        if (seat > 3) throw new Error(`decodeDeal: card ${value} has invalid seat ${seat}`);
        hands[seat].push(CARD_BY_VALUE[value]);
    }
    return hands;
}

/**
 * Cards -> 52-bit mask, returned as a Number.
 *
 * Bit `value` is set when that card is in the set. The largest possible mask is
 * 2^52 - 1, comfortably inside Number.MAX_SAFE_INTEGER (2^53 - 1), so the value
 * survives a round trip through SQLite's INTEGER and through JSON exactly.
 *
 * BigInt is used to build it because JavaScript's bitwise operators truncate to
 * 32 bits -- `1 << 51` is not 2^51, it is 2^19. That silent wrap is the whole
 * reason this helper exists rather than being inlined at call sites.
 */
function encodeCards(cards) {
    let mask = 0n;
    for (const card of cards || []) {
        const value = card.value !== undefined ? card.value : cardValue(card);
        if (value < 0 || value >= DECK_SIZE) {
            throw new Error(`encodeCards: card value ${value} out of range`);
        }
        const bit = 1n << BigInt(value);
        if (mask & bit) throw new Error(`encodeCards: duplicate card ${value}`);
        mask |= bit;
    }
    return Number(mask);
}

/** 52-bit mask -> cards, ascending by value (which is Big2Rules sort order). */
function decodeCards(mask) {
    const cards = [];
    let bits = BigInt(mask || 0);
    while (bits > 0n) {
        // Lowest set bit first, so output is already ascending.
        const lowest = bits & -bits;
        const value = bitLength(lowest) - 1;
        if (value >= DECK_SIZE) throw new Error(`decodeCards: bit ${value} is not a card`);
        cards.push(CARD_BY_VALUE[value]);
        bits ^= lowest;
    }
    return cards;
}

function bitLength(value) {
    let length = 0;
    while (value > 0n) {
        value >>= 1n;
        length++;
    }
    return length;
}

function popcount(mask) {
    let bits = BigInt(mask || 0);
    let count = 0;
    while (bits > 0n) {
        bits &= bits - 1n;
        count++;
    }
    return count;
}

// Action codes on mlog_action. Append only.
const ACTION = {
    PASS: 0,
    PLAY: 1,
    AUTO_PASS: 2   // server-generated by the 2-of-Spades rule, not a decision
};

// Who or what produced the ply. Append only.
const SOURCE = {
    HUMAN: 0,
    AUTO_PASS_PREF: 1,  // the player's auto-pass setting acted for them
    BOT: 2,
    SERVER_RULE: 3,     // 2S auto-pass
    BOT_FALLBACK: 4     // advanced bot errored; heuristic answered this ply only
};

// Bit flags on mlog_action.flags. Append only.
const FLAG = {
    THINK_CLAMPED: 1 << 0,
    TURN_DISCONNECTED: 1 << 1
};

/**
 * think_ms ceiling. A disconnected player's turn stalls rather than
 * auto-passing, bounded only by room cleanup at 30 minutes (multiplayer) or
 * 24 hours (single-player), so an unclamped value records how long someone was
 * away. Two minutes is deliberately generous: it should destroy no legitimate
 * deliberation, only values nobody would train on.
 *
 * This is a lossy transform, so it is pinned to SCHEMA_VERSION -- changing it
 * makes old and new rows incomparable.
 */
const THINK_MS_CEILING = 120000;

function clampThinkMs(rawMs) {
    if (rawMs === null || rawMs === undefined) return { thinkMs: null, clamped: false };
    const ms = Math.max(0, Math.round(rawMs));
    return ms > THINK_MS_CEILING
        ? { thinkMs: THINK_MS_CEILING, clamped: true }
        : { thinkMs: ms, clamped: false };
}

module.exports = {
    DECK_SIZE,
    CARD_BY_VALUE,
    cardValue,
    encodeDeal,
    decodeDeal,
    encodeCards,
    decodeCards,
    popcount,
    ACTION,
    SOURCE,
    FLAG,
    THINK_MS_CEILING,
    clampThinkMs
};
